### ISSUE TITLE
Plot snapshots in readme

### ISSUE THREAD

**Issue by praharshapm** [neethujohny/avsddac_3v3#2]
Hi Neethu,
In my opinion, the DNL vs input code and INL vs input code plot snapshots can be added in the readme in their respective sections.

**Comment by neethujohny** [comment]
Hi Praharsha,

Added the DNL and INL plots under their sections. Please have a look at it.

**Comment by praharshapm** [comment]
Hi Neethu,
Yes. It looks good.
